"""Department codes and school codes for use with Yale Courses API."""

DEPARTMENTS = {
    "F&ES": "School of Forestry & Environmental Studies",
    "EMST": "Early Modern Studies",
    "MHHR": "Material Hist of Human Record",
    "PTB": "Translational Biomedicine",
    "ACT": "Acting",
    "USAF": "Aerospace Studies",
    "AFAM": "African American Studies",
    "AFST": "African Studies",
    "AMST": "American Studies",
    "ANTH": "Anthropology",
    "AMTH": "Applied Mathematics",
    "APHY": "Applied Physics",
    "ARCG": "Archaeological Studies",
    "ARCH": "Architecture",
    "ART": "Art",
    "ASTR": "Astronomy",
    "B&BS": "Biological & Biomedical Sci",
    "BIOL": "Biology",
    "BENG": "Biomedical Engineering",
    "BRST": "British Studies",
	"C&MP": "Cell & Molecular Physiology",
    "CBIO": "Cell Biology",
    "CENG": "Chemical Engineering",
    "CHEM": "Chemistry",
    "CHLD": "Child Study Center",
    "CLSS": "Classics",
    "CGSC": "Cognitive Science",
    "CPLT": "Comparative Literature",
    "CB&B": "ComputationalBio&Bioinformatic",
    "CPSC": "Computer Science",
    "DES": "Design",
    "DRST": "Directed Studies",
    "DIR": "Directing",
    "REL": "Divinity School",
    "DRMA": "Drama",
    "DTG": "Dramaturgy & Dramatic Crit",
    "EPS": "Earth and Planetary Sciences",
    "EALL": "East Asian Langs & Lits",
    "EAST": "East Asian Studies",
    "E&EB": "Ecology & Evolutionary Biology",
    "ECON": "Economics",
    "EDST": "Education Studies",
    "EENG": "Electrical Engineering",
    "ENRG": "Energy Studies",
    "ENAS": "Engineering & Applied Science",
    "ESL": "English as Second Language",
    "ENGL": "English Language & Literature",
    "ENV": "Environment",
    "ENVE": "Environmental Engineering",
    "EVST": "Environmental Studies",
    "E&PH": "Epidemiology & Public Health",
    "EP&E": "Ethics, Politics, & Economics",
    "ER&M": "Ethnicity, Race, & Migration",
    "E&RS": "European and Russian Studies",
    "EXPA": "Experimental Pathology",
    "FILM": "Film & Media Studies",
    "FREN": "French",
    "GENE": "Genetics",
    "GMAN": "Germanic Langs & Lits",
    "GLBL": "Global Affairs Program",
    "GSAS": "Graduate School",
    "HLTH": "Health Studies",
    "HELN": "Hellenic Studies",
    "HSHM": "Hist of Science, Hist of Med",
    "HIST": "History",
    "HSAR": "History of Art",
    "0056": "History/Sci, History/Med Major",
    "HUMS": "Humanities",
    "IBIO": "Immunobiology",
    "INP": "Interdpt Neuroscience Pgm",
    "IMED": "Investigative Medicine",
    "ITAL": "Italian Language & Literature",
    "JDST": "Judaic Studies",
    "LAST": "Latin American Studies",
    "LAW": "Law School",
    "LING": "Linguistics",
    "MGMT": "Management",
    "MATH": "Mathematics",
    "MENG": "Mechanical Engineering",
    "MDVL": "Medieval Studies",
    "MBIO": "Microbiology",
    "MMES": "Modern Middle Eastern Studies",
    "MB&B": "Molecular Biophysics & Biochem",
    "MCDB": "Molecular, Cellular & Dev Biol",
    "MUSI": "Music Dept",
	"MUS": "Music School",
	"NAVY": "Naval Science",
	"NELC": "Near Eastern Languages & Civilizations",
	"NBIO": "Neurobiology",
	"NSCI": "Neuroscience",
	"PATH": "Pathology",
	"PHAR": "Pharmacology",
	"PHIL": "Philosophy",
	"OLPA": "Physician Assistant Online Pgm",
	"620": "Physicians Associate Program",
	"PHYS": "Physics",
	"PLW": "Playwriting",
	"PLSC": "Political Science",
	"PORT": "Portuguese",
	"PSYC": "Psychology",
	"RLST": "Religious Studies",
	"RNST": "Renaissance Studies",
	"RSEE": "Russian & East Europe Studies",
	"MGT": "School of Management",
	"MED": "School of Medicine",
	"NURS": "School of Nursing",
	"SLAV": "Slavic Languages & Literatures",
	"SOCY": "Sociology",
	"SND": "Sound Design",
	"SAST": "South Asian Studies",
	"SEAS": "Southeast Asia Studies",
	"SPAN": "Spanish",
	"SP&P": "Spanish & Portuguese",
	"SMGT": "Stage Management",
	"STAT": "Statistics",
	"S&DS": "Statistics and Data Science",
	"SUMM": "Summer Programs",
	"TD&P": "Technical Design & Production",
	"TMGT": "Theater Management",
	"THST": "Theater Studies",
	"WGSS": "Women's Gender & Sexuality Studies",
    "YALC": "Yale College",
	"YCCS": "Yale College College Seminar"
}

SCHOOLS = {
    "GB": "School of Global Affairs",
    "AC": "Architecture School",
    "AT": "Art School",
    "DI": "Divinity School",
    "DR": "Drama School",
    "GS": "Graduate School of Arts & Sci",
    "NR": "Nursing School",
    "PA": "Physician Associate Program",
    "PH": "Public Health",
    "MG": "School of Management",
    "MU": "School of Music",
    "FS": "School of the Environment",
    "SU": "Summer Session",
    "YC": "Yale College"
}